models/sence/craxnhax/sence_anonymous2.mdl
models/sence/craxnhax/sence_bossarm.mdl
models/sence/craxnhax/sence_boss.mdl
sound/sence/craxnhax/seekndestroy_keygen.wav
models/player/mrunknown/mrunknown.mdl
models/player/sence/sence.mdl
models/player/sence/sence.bmp
maps/craxnhax.cfg
maps/craxnhax.res
maps/craxnhax.txt
maps/craxnhax1.res
maps/craxnhax1.txt
maps/craxnhax1_motd.txt
maps/craxnhax2.cfg
maps/craxnhax2.res
maps/craxnhax2.txt
maps/craxnhax2_motd.txt
maps/craxnhax_motd.txt