// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/min_night_bk.tga
gfx/env/min_night_dn.tga
gfx/env/min_night_ft.tga
gfx/env/min_night_lf.tga
gfx/env/min_night_rt.tga
gfx/env/min_night_up.tga
kr_text_log.wad
minecraft2.wad
minecraft_def.wad
models/mc_defence/bullet_arrow.mdl
models/mc_defence/enderknight.mdl
models/mc_defence/item_ammobox.mdl
models/mc_defence/item_apple.mdl
models/mc_defence/mc_enderdragon.mdl
models/mc_defence/mc_sentry.mdl
models/mc_defence/mc_wood.mdl
models/mc_defence/npc_purple_heart.mdl
models/mc_defence/p_axe.mdl
models/mc_defence/p_bow.mdl
models/mc_defence/p_gapple.mdl
models/mc_defence/p_gun.mdl
models/mc_defence/p_sword.mdl
models/mc_defence/skeleton.mdl
models/mc_defence/v_axe.mdl
models/mc_defence/v_bow.mdl
models/mc_defence/v_gapple.mdl
models/mc_defence/v_gun.mdl
models/mc_defence/v_sword.mdl
models/mc_defence/w_arrow.mdl
models/mc_defence/w_axe.mdl
models/mc_defence/w_bow.mdl
models/mc_defence/w_gapple.mdl
models/mc_defence/w_gun.mdl
models/mc_defence/w_sword.mdl
models/mc_defence/young_knight.mdl
models/mc_defence/zombie.mdl
models/mc_defence/zspawner.mdl
models/player/mc_steve/mc_steve.bmp
models/player/mc_steve/mc_steve.mdl
sound/mc_defence/battle.mp3
sound/mc_defence/dragonborn.mp3
sound/mc_defence/minecraft.mp3
sound/mc_defence/npc/claw_miss1.wav
sound/mc_defence/npc/claw_miss2.wav
sound/mc_defence/npc/claw_strike1.wav
sound/mc_defence/npc/claw_strike2.wav
sound/mc_defence/npc/claw_strike3.wav
sound/mc_defence/npc/zo_alert10.wav
sound/mc_defence/npc/zo_alert20.wav
sound/mc_defence/npc/zo_alert30.wav
sound/mc_defence/npc/zo_attack1.wav
sound/mc_defence/npc/zo_attack2.wav
sound/mc_defence/npc/zo_idle1.wav
sound/mc_defence/npc/zo_idle2.wav
sound/mc_defence/npc/zo_idle3.wav
sound/mc_defence/npc/zo_idle4.wav
sound/mc_defence/npc/zo_pain1.wav
sound/mc_defence/npc/zo_pain2.wav
sound/mc_defence/sevenminutes.ogg
sprites/mc_defence/weapon_bow.txt
sprites/mc_defence/weapon_gun.txt
sprites/mc_defence/weapon_tnt.txt
